ProFit/objects/Attendee__c.object
<CustomObject>
    <description>Attendee Object for Profit App</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFit/objects/Event__c.object
<CustomObject>
    <description>Events for Pro Fit App</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>Ending Date</description>
        <inlineHelpText>Ending Date</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the Event</description>
        <inlineHelpText>Location of the Event</inlineHelpText>
        <label>Event Location</label>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event Organizer</description>
        <inlineHelpText>Event Organizer</inlineHelpText>
        <label>Event Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Live?</description>
        <inlineHelpText>Live?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Title</description>
        <inlineHelpText>Event Title</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Starting Date</description>
        <inlineHelpText>Starting Date</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Attendee__c.object
<CustomObject>
    <description>Event-Attendee object for Pro Fit App</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Event Attendees</description>
        <inlineHelpText>Event Attendees</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Event Search</description>
        <inlineHelpText>Event Search</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit/objects/Event_Location__c.object
<CustomObject>
    <description>Location Object for Pro Fit App</description>
    <label>Event Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Organizer__c.object
<CustomObject>
    <description>Event Organizer Object for Pro Fit App</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/classes/AttendeeEventsService.cls
public with sharing class AttendeeEventsService {
  @AuraEnabled(cacheable = true)
  public static List<Event_Attendee__c> upcomingEvents(String attendeeId) {
    System.debug('Envoke Upcoming Events');
    List<Event_Attendee__c> eventLists = [
      SELECT
        Id,
        Name,
        Event__c,
        Event__r.Event_Location__c,
        Event__r.Event_Location__r.Name,
        Event__r.Event_Organizer__c,
        Event__r.Event_Organizer__r.Name,
        Event__r.Name__c,
        Event__r.Start_Date_Time__c,
        Event__r.End_Date_Time__c
      FROM Event_Attendee__c
      WHERE
        Attendee__c = :attendeeId
        AND Event__r.Start_Date_Time__c >= today
        AND Event__r.Live__c = true
    ];
    return eventLists;
  }

  @AuraEnabled(cacheable = true)
  public static List<Event_Attendee__c> pastEvents(String attendeeId) {
    List<Event_Attendee__c> eventLists = [
      SELECT
        Id,
        Name,
        Event__c,
        Event__r.Event_Location__c,
        Event__r.Event_Location__r.Name,
        Event__r.Event_Organizer__c,
        Event__r.Event_Organizer__r.Name,
        Event__r.Name__c,
        Event__r.Start_Date_Time__c,
        Event__r.End_Date_Time__c
      FROM Event_Attendee__c
      WHERE Attendee__c = :attendeeId AND Event__r.Start_Date_Time__c < today
    ];
    return eventLists;
  }
}