ProFit/objects/Event__c.object
<CustomObject>
    <description>Events for Pro Fit App</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>Ending Date</description>
        <inlineHelpText>Ending Date</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the Event</description>
        <inlineHelpText>Location of the Event</inlineHelpText>
        <label>Event Location</label>
        <referenceTo>Event_Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event Organizer</description>
        <inlineHelpText>Event Organizer</inlineHelpText>
        <label>Event Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Live?</description>
        <inlineHelpText>Live?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Title</description>
        <inlineHelpText>Event Title</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Starting Date</description>
        <inlineHelpText>Starting Date</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Location__c.object
<CustomObject>
    <description>Location Object for Pro Fit App</description>
    <label>Event Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Organizer__c.object
<CustomObject>
    <description>Event Organizer Object for Pro Fit App</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/classes/EventRestService.cls
@RestResource(urlMapping = '/api/Event__c/*')

/* Callback URL: https://login.salesforce.com/services/oauth2/callback
///Post URL: https://openminds2--capsandbox.my.salesforce.com/services/oauth2/token?
    - grant_type
    - client_id
    - client_secret
    - username
    - password
///Get URL: https://openminds2--capsandbox.my.salesforce.com/services/apexrest/api/Event__c/*Event ID* */

global with sharing class EventRestService {
    @HTTPGet
    global static Event__c doGetEvt(){
        RestRequest req = RestContext.request;
        RestResponse resp = RestContext.response;
        String evtId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1); 
        Event__c result = [Select Id, Name__c, Event_Location__r.Name, Event_Organizer__r.Name, Live__c, Start_Date_Time__c, End_Date_Time__c from Event__c where Id =: evtId];
        return result;
    }
}